### ISSUE TITLE
--separator argument broken in v0.3.8

### ISSUE THREAD

**Issue by ralfproba** [opencultureconsulting/openrefine-client#11]
Hi,
i have a problem with the --separator argument
this is my command in powershell: 
.\openrefine-client_0-3-8_windows.exe -H 192.168.110.209 -P 3333 --create=20207.txt --projectName=temp --encoding=ISO-8859-1 --separator=";"

the semicolon dont work --> i check the web gui --> open project --> temp --> about 
no separator is shown in the Import option metadata (JSON) line
i try it with comma , and this works fine and is shown in the Import option metadata (JSON) line

**Comment by felixlohmeier** [comment]
I can confirm this bug report.

This regression was introduced with v0.3.8 (latest working version: v0.3.7)

I am currently working on functional tests. This may take 1-2 weeks. After that I will fix this and any other errors and release a new version. Sorry for any inconvenience due to low test coverage.

In the meantime you could try v0.3.7: https://github.com/opencultureconsulting/openrefine-client/releases/download/v0.3.7/openrefine-client_0-3-7_windows.exe

I would also suggest to add `--format csv` to your command (or rename your file 20207.txt o 20207.csv) to explicitly define the input format (and not rely on OpenRefine to guess the format).

**Comment by ralfproba** [comment]
you are the best 👍 

my original file has the ending .csv --> i think this is another bug
when i import this csv file with openrefine-client i have a single line project in openrefine (problem with the rowSeparator?? --> i don´t test this)
when i import with txt or --format=line-based i have multiple lines without header

and last but not least i think the argument headerLines have a problem too
in the above import with format=line-based i can´t set --headerLines=1

**Comment by felixlohmeier** [comment]
Could you share the file (if it is not confidential) for debugging? mail@felixlohmeier.de

**Comment by felixlohmeier** [comment]
Thank you very much for providing the test file.
* The separator argument should work with csv or tsv format, this is definitely a bug.
* headerLines seems to be OK. OpenRefine's line-based importer does not provide an option to define a separator or header. The client does not prevent additional arguments not supported by the chosen OpenRefine importer.

![Screenshot_2020-08-07 OpenRefine](https://user-images.githubusercontent.com/2117205/89658299-ad440480-d8ce-11ea-991e-caeda0c7a79a.png)

The help screen lists corresponding formats for each argument
```
    --headerLines=HEADERLINES
                        (csv,tsv,txt/fixed-width,xls,xlsx,ods), default: 1,
                        default txt/fixed-width: 0
(...)
    --linesPerRow=LINESPERROW
                        (txt/line-based), default: 1
(...)
    --separator=SEPARATOR
                        (csv,tsv), default csv: , default tsv: \t
```
I admit that this is not very user-friendly. If I were to rewrite the client, I would choose a syntax with subcommands like `create csv --separator`. Then `create csv --help` would list all (and only these) available options for the csv format.

**Comment by felixlohmeier** [comment]
Hi @ralfproba, I have just released a new version that contains a fix for the separator argument. Would you like to try it out? I would appreciate your feedback. https://github.com/opencultureconsulting/openrefine-client/releases/download/v0.3.9/openrefine-client_0-3-9_windows.exe
