### ISSUE TITLE
add CSRF token to API calls (introduced with OpenRefine 3.3)

### ISSUE THREAD

**Issue by msaby** [opencultureconsulting/openrefine-client#7]
Hi
I'm trying to use your client. I launched openrefine (3.3beta), downloaded openrefine-client it and launched the command (Win10, powershell)
.\openrefine-client_0-3-8_windows.exe --create .\duplicates.csv

I got this error. I am missing a step ?

Traceback (most recent call last):
  File "refine.py", line 36, in <module>
  File "google\refine\__main__.py", line 251, in main
  File "google\refine\cli.py", line 127, in create
  File "google\refine\refine.py", line 281, in new_project
Exception: Project not created
[9952] Failed to execute script refine

**Comment by felixlohmeier** [comment]
Currently the openrefine-client only supports OpenRefine up to version 3.2.

OpenRefine 3.3 introduces CSRF tokens:
> Cross-Site Request Forgery (CSRF) protection was added to POST API endpoints. If you rely on OpenRefine's server API you will need to adapt your calls accordingly (#2164)
(https://github.com/OpenRefine/OpenRefine/releases/tag/3.3-beta)

I will update the client [accordingly](https://github.com/OpenRefine/OpenRefine/pull/2182#issuecomment-542628156), probably next month.

**Comment by jqnatividad** [comment]
Hi @felixlohmeier, first off, thanks for this amazing automation.  I'm checking to see when you plan to support OpenRefine 3.3.

I'm using openrefine batch quite successfully with https://github.com/dathere/covid19-time-series-utilities.  

Though it works, it just shows a lot of console warnings.

**Comment by felixlohmeier** [comment]
Hi @jqnatividad, thanks a lot! I didn't make it back in December and I'm on parental leave now. I'm planning on it for the next quarter, so by the end of June.

**Comment by felixlohmeier** [comment]
I have done some experiments with cURL recently. Here is a bash script that supports batch processing with OpenRefine 3.3:
https://gist.github.com/felixlohmeier/d76bd27fbc4b8ab6d683822cdf61f81d

Will update the openrefine-client by the end of July. Sorry for the delay.

**Comment by felixlohmeier** [comment]
release [v0.3.10](https://github.com/opencultureconsulting/openrefine-client/releases/tag/v0.3.10) now works with OpenRefine 3.3+
